### ISSUE TITLE
Selecting alternate workspace renders Mutter icons and menus invisible

### ISSUE THREAD

**Issue by M1chaelM** [tfoote/test_novnc#1]
When logging in to novnc locally (or remotely via cloudsim), the user is initially presented with the option of selecting the Mutter Windows manager. Selecting Mutter brings up a graphical environment as expected:

![mutter_init](https://user-images.githubusercontent.com/8611855/111545284-0ad8e300-8733-11eb-826a-4fd8699b8ff0.png)

However, clicking any of the virtual workspace icons in the lower menu causes all features to become invisible:

![mutter_invisible](https://user-images.githubusercontent.com/8611855/111545370-34920a00-8733-11eb-9f04-6ffbe4a3f081.png)

Some of the elements, such as the menu and calendar still work if you know where to click:

![mutter_secret_menu](https://user-images.githubusercontent.com/8611855/111545631-95b9dd80-8733-11eb-90d1-d8b54ba2ef1b.png)

However, I don't see a way to restore the desktop without killing and restarting the Docker image (changing the icon set, theme or other appearance settings doesn't seem to help). An easy workaround for now is to either avoid clicking on these virtual spaces, or to select OpenBox instead of Mutter.

**Comment by tfoote** [comment]
I'm hoping to get rid of the ambiguity. One or more of your selected dependencies is bringing in mutter. Openbox is the recommended one for this distro.

**Comment by tfoote** [comment]
Fixed in 952ba04a924ead5e4e5a5f45f71c600126b70bfb
