### ISSUE TITLE
Set MATLAB Python version 

### ISSUE THREAD

**Issue by bsb808** [tfoote/test_novnc#16]
When running `rosinit` in MATLAB get an error that the Python version is not set.  See last section of https://wiki.nps.edu/display/MRC/Matlab+on+Cloudsim

Could we set this as a MATLAB global setting or startup command so that users do not have to remember to set this each time.

**Comment by bsb808** [comment]
Perhaps a global startup.m script: https://www.mathworks.com/help/matlab/matlab_env/startup-options.html

**Comment by bsb808** [comment]
Can pass the command on startup with the command

```
matlab -licmode online -r "pyenv('Version','/usr/bin/python2')"
```

Added this to the wiki.  https://wiki.nps.edu/display/MRC/Matlab+on+Cloudsim

Re-assigning to @M1chaelM in case he would like to establish a global alias

**Comment by M1chaelM** [comment]
This is fixed in the image now, and I updated the Wiki.
