### ISSUE TITLE
Package additions

### ISSUE THREAD

**Issue by bsb808** [tfoote/test_novnc#5]
Could we add the following to the image:

* sudo apt install ros-noetic-rosbash
* tree: `sudo apt install tree`
* ros tutorials: `sudo apt-get install ros-<distro>-ros-tutorials`
* Screen capture application - to take screen grabs locally.

**Comment by M1chaelM** [comment]
@tfoote I created a branch with edits to address these requests and tested it locally, but I don't have permissions to push it or create a PR. Would you mind granting these?

**Comment by tfoote** [comment]
fixed in #8
