### ISSUE TITLE
Add source line to .bashrc

### ISSUE THREAD

**Issue by bsb808** [tfoote/test_novnc#6]
Could we add `https://github.com/tfoote/test_novnc/issues` to the basrc file for the developer user?

**Comment by tfoote** [comment]
This doesn't look like something to directly add to the `.bashrc`

Is this what you meant to paste?

**Comment by bsb808** [comment]
Sorry about that.  Here was the suggested added line.

```
source /opt/ros/noetic/setup.bash
```

**Comment by M1chaelM** [comment]
Resolved by PR #18.
